### PR TITLE
Use GitHub actions

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Looks like when a non-committer does this change, nothing happens?

**Comment by RyanGlScott** [comment]
Thanks! I plan to get around to porting everything over to GitHub Actions at some point, but help is definitely appreciated.

> Looks like when a non-committer does this change, nothing happens?

Ah, that's a bit unfortunate. Nevertheless, I'm fairly confident that this will do what I would want it to do. I only have one additional request: can you change the README to switch from a Travis badge to a GitHub Actions badge? [Here](https://github.com/goldfirere/singletons/commit/2175c15e689f6bde2ab6a92549f14ddf1376c281) is an example to draw from.

**Comment by phadej** [comment]
Done.

My plan is to make `cabal-docspec` PR here first.
Also, as I'm on it, I'll make an explicitly-safe PR as well.
(And then climb the dependency tree towards `semigroupoids` + `lens`, making stuff safe and build-type: Simple)

**Comment by RyanGlScott** [comment]
Just to clarify, is making everything explicitly Safe a prerequisite for `cabal-docspec`? Or is that a separate effort entirely?

Also, thanks! I'll go ahead and merge this in an attempt to "unstick" CI.

**Comment by phadej** [comment]
They are separate, but as I'm traversing the kmettverse, I can well do both.

**Pull request merged**
